### ISSUE TITLE
A Couple of Questions : Silverstripe & whm-server-status

### ISSUE THREAD

**Issue by mindlash** [nuevvo/engintron#18]
The speed difference with nginx is incredible.  I had to unfortunately uninstall it due to one of my clients 'admin' sections not being accessible.  To that end, I would much rather run this than not.  

Question/Issue 1:
The site in question uses SilverStripe (albeit an older version) which has issues with nginx.  I did find some rules of sorts for nginx/fast_cgi and was wondering if you could help me understand (or better translate) their rules into what would work for your version in engintron.

https://gist.github.com/chtombleson/8703899

Question/Issue 2:
I've noticed that I can no longer access whm-server-status from command line:
$ lynx localhost/whm-server-status

In the error logs it mentions a 404 from trying to access it from another location, such as a default nginx/htdocs location (the exact path alludes me at the moment).  How can this be restored, as the only way currently to see server-status is from within WHM itself.

=============

Thanks!

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

The WHM server status page won't have an issue getting executed as well due to the way the whole proxying is currently achieved.
