### ISSUE TITLE
Restore original visitor IP

### ISSUE THREAD

**Issue by Nirjonadda** [nuevvo/engintron#33]
Hello,
Please let me know does it Support restore original visitor IP? My site user IP logs show server IPs using Nginx? Does you added any module for a Scrutinize User's IP address? Are you include mod_proxy/Reverse Proxy?
Thanks

**Comment by AgentGod** [comment]
Hi, 
maybe you should check Home » Service Configuration » Apache Configuration » Piped Log Configuration

Regards

**Comment by Nirjonadda** [comment]
You are does not understanding, what i am asking? I am asked to does it Support restore original visitor IP? Not the Piped Log Configuration.

**Comment by Friendbg** [comment]
Nirjonadda, I had the same problem, and I fix it. The problem was because after I install engintron, I update cpanel from easyapache. Then I had this strannge issue with visitor ips and I saw only server ip. I uninstall engintron and install it again and the problem was fixed.

I hope this can help you with yours.
