### ISSUE TITLE
Uninstall leaves cPanel httpd dead

### ISSUE THREAD

**Issue by Tragidy** [nuevvo/engintron#38]
I installed and removed, it leaves apache un usable and un connectable after uninstalling on latest RELEASE of cpanel.

Says removal went great, so be aware you will have to reconfigure lots of things on your cpanel server to have it work properly after removing this script.

**Comment by Tragidy** [comment]
Leaves all config files to port 8081 and virtual host resulting in cpanel pointing to cgi-sys/defaultwebpage.cgi all host even when you change port back, so like I said lots of work...

**Comment by Tragidy** [comment]
I configured Apache to use a different port by editing the following option under the "System" tab in "WHM Home » Server Configuration » Tweak Settings":

"Apache non-SSL IP/port"

Existing and new accounts were configured with the new port number in the Apache configuration file. You may want to try rebuilding it via:

Code:
/scripts/rebuildhttpdconf


This will fix your server quite fast but remember there still may be changes left undone this script is messy and does not work as intended.

**Comment by gbassoc** [comment]
yes, I agree same thing happened to me. I had to reinstall engintron to get things working properly again

**Comment by fevangelou** [comment]
The fix is to simply change the Apache port back to 80 and 443 (for secure content) in WHM's Tweak Settings. But in order for this to take effect, you also need to restart Apache.

It would greatly help if you guys could tell me which cPanel versions you're using.

**Comment by Tragidy** [comment]
WHM 11.48.0

**Comment by gbassoc** [comment]
11.48.0 (build 11)

**Comment by Friendbg** [comment]
Hi, add this at 935 line on engintron.sh :

sed -i 's/:8081/:80/g' /etc/httpd/conf/httpd.conf

and your websites will be live again after uninstalling engintron.

**Comment by sjafferali** [comment]
That isn't a permanent solution as it will be overwritten the next time the httpd.conf is rebuilt. The issue is that cPanel restores the old value from /var/cpanel/cpanel.config.cache after the sed command removes the line. 

root@cp [~]# sed -i  's/apache_port=0.0.0.0:8081$//' /var/cpanel/cpanel.config
root@cp [~]# /usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings
warn [whostmgr2] One or more key settings for “cp.xxxx.xxxx” were either not found in cPanel & WHM’s server configuration file (/var/cpanel/cpanel.config), or were present but did not pass validation.
warn [whostmgr2] The following settings were absent, but were restored from your cpanel.config.cache file:
warn [whostmgr2]     apache_port  = 0.0.0.0:8081

I submitted a pull request to update the sed command: https://github.com/nuevvo/engintron/pull/44

For the time being though, running the below commands manually after the uninstall will fix it. It will apply to subsequent rebuilds as well.

	sed -i 's/apache_port=0.0.0.0:8081$/apache_port=0.0.0.0:80/' /var/cpanel/cpanel.config
	/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

The uninstaller has also been fixed and the switched port is 8080 now so it works with those using CloudFlare as well for their sites.
