### ISSUE TITLE
SSL support ?

### ISSUE THREAD

**Issue by ArjenE** [nuevvo/engintron#40]
Is ssl handled bij nginx or apache ?

**Comment by Tokentools** [comment]
Looking for answer also, is SSL setup the same as for normal NGINX SSL? For example as per the details at this link 

https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html

**Comment by fevangelou** [comment]
SSL is not provided by default by Nginx. All SSL requests will simply be proxied to port 443 which is still used by Apache.

Since I recently updated Engintron to v1.5.0, it's easy to also configure SSL from within Nginx. But it would require the use of a shared SSL cert for the entire server. Or you could have exclusions per domains in order to use their existing SSL certificates.

Having Nginx also handle SSL requests also solves the problem with domains that don't have an SSL certificate and when you call these domains up you simply see your server's default page. ;)

**Comment by masteranalyze** [comment]
fev you mean an wildcard ssl ? or what do you mean by shared ssl cert?

If an shared ssl certificate will be setup instead of an private ssl,when the user will go to that webpage,if the certificate is shared it won`t display that annoy messaje ?! IF you wish to continue,etc and freak the user out ?!

As in an server,you can have more cpanel,each with their own domain name.
Some might have private ssl,some might not.

You could also need ssl only on some domains and not on all domains from the server.

In this case what is the best approach?!

**Comment by fevangelou** [comment]
No, it's an SSL certificate that can be used with multiple domains AND subdomains. It's called a UCC/SAN certificate and GoDaddy sells the cheapest one: https://ca.godaddy.com/web-security/ssl-certificate (it's the middle option)

If you'd want to use different SSL certificates, then some sort of exclusion should have to be possible (I suppose).

**Comment by masteranalyze** [comment]
will that certificate basically work on domains only ?Or in subdomains of the domains also ?!

From their info,is basically for 100 domains .com/net /org ,but that 100 i guess it does not reffer if you have 10 domains and 50 subdomains,you can use like that also !?So totally will be 60 used from 100?!

If you have any ideea about this.

**Comment by fevangelou** [comment]
I think the count is for naked domains but it's best to ask GoDaddy
directly.

One of things I wish to integrate in Engintron soon is the automated
generation of SSL certificates using Let's Encrypt which is 100% free.

**Comment by ArjenE** [comment]
"Is ssl handled bij nginx or apache ?"

Nginx is running on the shared ipv4 and ipv6 adres. Default cpanel apache is only running on the shared ipv4 adres. And not on the shared ipv6 adres...

If 443 is rerouted to apache 443. ipv6 connections are killed.

**Comment by fevangelou** [comment]
The Nginx definition does not currently support IPv6 if that's what you're asking. But that's easy to fix (I'll set it for 1.5.1).

Did you mean something else?

I don't understand why you mention the HTTPS port, since Nginx does not currently operate on that port...

**Comment by masteranalyze** [comment]
setup it for 1.5.1 . ipv6

+1  Let's Encrypt which is 100% free.Any ideea as they are in beta,if they will be out of beta?and if any problems can arrise from their beta?! https://letsencrypt.org/howitworks/technology/

Problem with the SSL is that sometimes improper config,or improper browser settings,will splash that annoying popup about the ssl certificate,if you wish to continue or not,witch scares the user away,more worst effect even of not having ssl,and having just http .

But as the whole world goes to https,problems like that,i think it will be solved.

**Comment by fevangelou** [comment]
If you see who backs up this effort, you'll understand Let's Encrypt is here to stay.

I think this issue is now resolved and any changes will be implemented in v1.5.1.

**Comment by masteranalyze** [comment]
of course is here to stay,i just saying that right now they have some problems,ovh is sponsoring them for this year,witch is an good thing!

**Comment by ArjenE** [comment]
is nginx running on port 80 only? Or is nginx also running on 443?.  On all other nginx solutions for cpanel nginx is running on port 80 and apache on 443 for the ssl sites. And 90% of the sites is runnig ssl and no advantage of nginx. :-( . Please enable ipv6 in the next release.  Cpanel ipv6 solution is crapy . Apache is not running on the shared ipv6 adres (just like the shared ipv4 adres)

**Comment by masteranalyze** [comment]
I think fev mentioned that up already : "SSL is not provided by default by Nginx. All SSL requests will simply be proxied to port 443 which is still used by Apache."
So port of nginx is 80,and apache 443,ssl will go through apache,so like you said no advantage of nginx.

Nginx is capable of handling both http and https.

Maybe in next version of engintron,fev you manage to do something,to have openssl or let`s encrypt ,and to be able to setup nginx to work for the https sites also.

**Comment by fevangelou** [comment]
There is no easy way to have Nginx in front of Apache's SSL port too. That would require valid SSL certificates. The only ways to bypass this is by using either Let's Encrypt SSL certificates or by having CloudFlare in front of all your sites. Obviously the first is easier to have, that's why it's on our roadmap for upcoming updates to Engintron.

**Comment by wtleaver** [comment]
AutoSSL is now support on cPanel, any chance we can get Engintron to support SSL assuming all domains have their own SSL certificate, or by inspecting the SSL hosts to discover which sites have SSL certificates and handling them?

**Comment by ampedd** [comment]
I would love to see this working as a large chunk of our sites are also running SSL now.

**Comment by eidmantas** [comment]
+1 interested as well.  I think it's in beta now.
https://features.cpanel.net/topic/provide-support-for-lets-encrypt-automated-certificate-management-ssl

We're considering installing Engitron over our stock WHM servers, but without SSL caching, basically are forced to go with another route (Maybe Varnish + Nginx as a proxy?). Is there any temp-fix for this?

**Comment by masteranalyze** [comment]
This is closed,follow up : https://github.com/engintron/engintron/issues/106#issuecomment-257725029

**Comment by youstable** [comment]
I am fully fed up with this error, is there any other option available to run Nginx on cPanel ?
