### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by fpinochet** [nuevvo/engintron#47]
On one of my web servers I have a caching issue where I have to clean up Nginx cache & temp files on Enintron in order for the latest changes on websites to appear. What can I do to fix this?

**Comment by fevangelou** [comment]
Is your site based on some open source cms?

**Comment by laurfx** [comment]
I have the same problem, i have Magento installed, fresh one with sample data, i put in htaccess no caching rule but with no effect...

It's a server side caching, i test it with http://seositecheckup.com/tools/page-cache-test-server-side-caching

Please, i need a fast fix, how i disable the cache?
Thanks

**Comment by Friendbg** [comment]
Hi, 

Open your file /etc/nginx/proxy.conf and put # in front of `proxy_cache   cpanel;`

Then restart nginx, and will not cache anymore. 

If you want this to be permanent (because your engintron.sh sync) you should open your engintron.sh and find `proxy_cache                                            cpanel;` and disable it.

Then run sh engintron.sh sync

Thanks

**Comment by laurfx** [comment]
Hello,

Not working, i commented all the lines of cache from all files and doesn't work, i still have cache. :(

Thanks

**Comment by fevangelou** [comment]
I see you're feeling adventurous! :)

Varnish will work almost like how Engintron (=Nginx) works now for cPanel. It has to cache most stuff in order to improve your site's performance. However Varnish is simpler to configure. You just need to define some exclusions for your content.

See my optimized Varnish config for more: https://gist.github.com/fevangelou/84d2ce05896cab5f730a/

This config is already deployed in sites doing dozens of millions of pageviews per month each, all around the world.

**Comment by laurfx** [comment]
Hello,

When i put that default.vcl in /etc/varnish i can't start anymore Varnish, i get this error:

# journalctl -xn
-- Logs begin at Sun 2015-11-15 14:13:51 EET, end at Sun 2015-11-15 22:34:05 EET. --
Nov 15 22:34:05 mydomain.tld varnishd[7708]: Message from VCC-compiler:
Nov 15 22:34:05 mydomain.tld varnishd[7708]: Symbol not found: 'req.request' (expected type BOOL):
Nov 15 22:34:05 mydomain.tld varnishd[7708]: ('input' Line 45 Pos 9)
Nov 15 22:34:05 mydomain.tld varnishd[7708]: req.request != "GET" &&
Nov 15 22:34:05 mydomain.tld varnishd[7708]: --------###########------------
Nov 15 22:34:05 mydomain.tld varnishd[7708]: Running VCC-compiler failed, exited with 2
Nov 15 22:34:05 mydomain.tld varnishd[7708]: VCL compilation failed
Nov 15 22:34:05 mydomain.tld systemd[1]: varnish.service: control process exited, code=exited status=2
Nov 15 22:34:05 mydomain.tld systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
-- Subject: Unit varnish.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit varnish.service has failed.
--
-- The result is failed.
Nov 15 22:34:05 mydomain.tld systemd[1]: Unit varnish.service entered failed state

I use Varnish 3.05. 
Do you have some varnish config for Magento?

Thanks

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

**Comment by masteranalyze** [comment]
I think nginx is much more better solution then varnish itself.

Varnish does not understand SSL,and practically you have to inter-conect varnish with nginx and complicate more your stack,in order to work ,in case you have an HTTPS website.

Varnish seems good only if you have http.

Nginx supports both http and https,and solves the problem you might have with varnish in case your website is https.

**Comment by fevangelou** [comment]
That is correct, although getting Nginx to proxy HTTPS to Varnish HTTP and back to Nginx HTTP is not hard. In fact, I've now personally mastered this sort of setup which will be part of a new project coming this summer :)

**Comment by masteranalyze** [comment]
When you ve done that setup,the results of nginx with varnish was more good then simple nginx ?!

Do you think ,it can work it out in engintron somehow?!

**Comment by fevangelou** [comment]
You don't need it when Nginx is already in reverse caching mode. Plus it would complicate things when it comes to logging visitor IPs. Nginx is just fine for that case. The setup I mention uses Nginx as the webserver, so having Nginx proxy content is kinda overkill. That's why we use Varnish in front of it.

**Comment by masteranalyze** [comment]
So the best option is practically simple,nginx right?!

**Comment by laurfx** [comment]
I have that problem 3 months ago... I don't remember how i fix it, but thanks anyway. Can you do something like php version switcher but with apache and nginx for accounts on cpanel? For example if i want to run on an account nginx and another apache (dedicated ips for both) . Thanks

**Comment by fevangelou** [comment]
The new setup is transparent and 100% safe to run with any type of site. So
there is really no benefit in excluding domains. You can have simply
proxied to Apache without any sort of static or dynamic content, but it's
impossible to have certain domains on Nginx and others on Apache
separately. This boils down to the fact that cPanel has a universal port
setting for Apache. So it's either Nginx or Apache responding on port 80.

Like I said, there is no reason to have Apache alone anymore.

Engintron 1.5 has been extensively tested for months now and on various
production servers of all sizes.

I believe it's a "must" for any cPanel server especially now that there is
no vhost sync and it actually works without any effort from the user's side.

The only manual thing you need to enable is micro-caching and this is a
matter of uncommenting a line in default.conf (full instructions in the
project's wiki).

**Comment by shivsingh7150** [comment]
Hello,

If anyone is facing such issue than i suggest you make code commented on 2 files. add # before each line:

You can see correct code below:

**For dynamic:**
/etc/nginx/proxy_params_dynamic

```
#proxy_cache					engintron_dynamic;
#proxy_cache_key				"$request_method$scheme$host$request_uri";
#proxy_cache_lock			on;
#proxy_cache_use_stale		updating;
#proxy_cache_valid			200 1s;
#proxy_ignore_headers		Expires Cache-Control Set-Cookie Vary;
```

**For static:**
/etc/nginx/proxy_params_static

```
#proxy_cache					engintron_static;
#proxy_cache_key				"$request_method$scheme$host$request_uri";
#proxy_cache_lock			on;
#proxy_cache_min_uses		1;
#proxy_cache_revalidate		on;
#proxy_cache_use_stale		error timeout updating http_500 http_502 http_503 http_504;
#proxy_cache_valid			200 301 302 1m; # Covers 200, 301 & 302 responses, caching time set to 1 minute
#proxy_ignore_headers		Set-Cookie;
```

**Comment by fevangelou** [comment]
If you do that then there is no point in having Engintron installed as you
get zero benefits... BTW to disable at least the 1s micro cache you only
need to comment out 1 line in default.conf.
