### ISSUE TITLE
dynamic cache....

### ISSUE THREAD

**Issue by masteranalyze** [nuevvo/engintron#51]
How does the dynamic cache works?

In stack overflow,i know they use an technique,they cache everything ,and when an user post an new post,the whole system only have to cache that post,and not the whole other post,for example if you have forum with 200 post,practically the cache will have to cache only the 201 post,as the other 200 are already cached.

This is very smart and take alot of pressure from the cpu,ram,etc .

How is the dynamic cache from nginx act and works ?Is working practically the same way for dynamic content ?Or haves an way to work smart ?

In order that dynamic websites to load also fast.Not only static or guest websites to load fast.

**Comment by fevangelou** [comment]
First off, Engintron by default will only cache static files. Think of it like your own CloudFlare on your server.

Secondly, if you wanna get better performance, you have to enable micro-caching. You do this by editing via WHM > Plugins > Engintron the main Nginx vhost file - default.conf - and commenting out the line 15 (check the comment there). This enables a 1 sec cache which works miracles when you have a large number of concurrent connections. That's why, if you enable this and run a simple Apache Benchmark test, you'll notice a site's serving capacity can raise from a few dozen - couple of hundred requests per second to thousands. I have Engintron deployed on various productions servers of all sizes and types (VPS or dedicated) and the best improvement I've seen was a Joomla site with lots of content going from less than 100 requests per second to 19,000!

Micro-caching works on GET and HEAD requests, never on POST. So even if you have user generated content, users won't notice and better still, guest users will be visiting an extremely fast website.

The case with StackOverflow is much different. It's one app, so they can handle caching differently so it can't be compared to how caching would work on a single server.

If you deploy Engintron, I'd like your feedback with micro-caching on :)

**Comment by masteranalyze** [comment]
I will test it also on dedicated,once cpanel team,maybe solve that bug on easyapache 4 that we talked about earlier.

And i will use it for joomla too.

From your reports and test benchmarks comparated to the initial varnish implementation you did for joomla,this one is more good or ? 

Maybe you can provide some numbers ,varnish vs nginx.

And what the heck happened when from 100 request seconds did go to 19.000? It was some kind of attack or suddenly social traffic spike ?!

"Micro-caching works on GET and HEAD requests, never on POST. So even if you have user generated content, users won't notice and better still, guest users will be visiting an extremely fast website."

The case of stackoverflow,i gaved just an example,as i know some people from their tech staff,and they work like on cache.

So if you enable the 1 sec cache that does miracles,and you have 100 post and an users comes and post the 101 comment,the 100 post will be already cache ?And it only cache 1 post  ?And not 101 post back again?That is the point....

**Comment by fevangelou** [comment]
You can't realy compare Varnish with Nginx. Varnish is for reverse proxy & caching only, not serving. Nginx is a full webserver with both reverse proxy/caching and serving capabilities.

My company uses Varnish with Nginx and PHP5-FPM on Ubuntu servers, without cPanel. In fact, I'm working on a small admin panel for all that, which I plan on releasing by the summer. The performance there does not compare to anything else.

As for the site I mentioned, the test was an Apache Benchmark, not an actual traffic spike. The trick with microcaching is pretty simple: keep a 1 second cache. If you have 100s of requests per second, only 1 will be served directly from Apache, all the rest from the server. Nginx is perfect for that (unlike Varnish which I don't know if it's capable for such short caching times) and it's also a recommended way to serve dynamic content, coming from the Nginx creators themselves.

**Comment by masteranalyze** [comment]
And that 1 second cache setup,will do the whole miracle on the whole dynamic content ??

I really hope cpanel solves fast with easyapache4,as i really need to test this out!

**Comment by fevangelou** [comment]
Correct. I hate to break it to you though, but I doubt cPanel will resolve the issue fast. Besides, EA4 is still considered beta, so they are kind of covered against their users.

**Comment by masteranalyze** [comment]
Don`t worry,i will help you,so they can solve it soon....maybe even this week!

Of course they are covered,they are all the time covered!

**Comment by masteranalyze** [comment]
Till next week,we mostly should have an update,i spoked with them on phone,i will keep track on this.

If we won`t have it,like they promised,i`m going down to easyapache 3,until things are fixed and out totally of beta!
Either way this will be solved...but it`s good to keep on eye on easyapache 4 solving of the problem,as easyapache4 sooner or later will become standard,and they might even drop easyapache3,once ea4 works.

p.s:fev do you have any the pecl pear on ea3,does have any problem?As i want to put the APCU,and give it try,as this is another reason i consider back to ea3,as this is not fixed for ea4 and no timeframe at all for when this is going to be solved.

**Comment by fevangelou** [comment]
Follow the guide for installing APC(u) in this project's wiki: https://github.com/nuevvo/engintron/wiki/10.-Beyond-Engintron:-Install-APC(u)-in-cPanel

The wiki has many more optimization guides too.

Considering this issue resolved as well.

**Comment by masteranalyze** [comment]
thanks fev,for it,i will take an look,just get back to easyapache3,after that i will deploy engintron.

I saw that basically when joomla will use nginx instead of apache,i have to redo some settings according to this guide : https://docs.joomla.org/Nginx ?! 

As mostly i use joomla!

**Comment by fevangelou** [comment]
Not really, if you use Engintron, you don't need to change anything either in .htaccess files or in Nginx's configuration.

**Comment by masteranalyze** [comment]
good to hear that,i will give it an spin soon,did get back in ea3 meantime!
